import { Course, Opportunity } from '@/types';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'mock-opp-1',
    title: 'Kazakhstan Youth Hackathon',
    description: '48-hour hackathon for high school students. Build a project that solves a local problem.',
    category: 'Programming',
    format: 'online',
    grade_min: 9,
    grade_max: 12,
    deadline: '2026-07-15',
    requirements: ['Grades 9-12', 'Basic coding knowledge', 'Team of 2-4'],
    benefits: ['Prizes', 'Mentorship', 'Certificates'],
    link: 'https://example.com/hackathon',
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-opp-2',
    title: 'Summer Research Program',
    description: '6-week research program in STEM fields with university mentors.',
    category: 'Science',
    format: 'hybrid',
    grade_min: 10,
    grade_max: 11,
    deadline: '2026-06-30',
    requirements: ['Grades 10-11', 'STEM interest', 'Recommendation letter'],
    benefits: ['Research experience', 'Publication opportunity'],
    link: 'https://example.com/research',
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-opp-3',
    title: 'Business Startup Competition',
    description: 'Pitch your startup idea to investors and win seed funding.',
    category: 'Business',
    format: 'offline',
    grade_min: 10,
    grade_max: 12,
    deadline: '2026-08-01',
    requirements: ['Grades 10-12', 'Business idea', 'Pitch deck'],
    benefits: ['Funding', 'Networking', 'Incubation'],
    link: 'https://example.com/startup',
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-opp-4',
    title: 'SAT Prep Scholarship',
    description: 'Full scholarship for SAT preparation course including practice tests.',
    category: 'Academic',
    format: 'online',
    grade_min: 11,
    grade_max: 11,
    deadline: '2026-07-20',
    requirements: ['Grade 11', 'Minimum GPA 3.5'],
    benefits: ['Free SAT prep', 'Study materials'],
    link: 'https://example.com/sat',
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-opp-5',
    title: 'Volunteer Teaching Program',
    description: 'Teach younger students in rural areas. Gain leadership experience.',
    category: 'Social Impact',
    format: 'offline',
    grade_min: 9,
    grade_max: 12,
    deadline: '2026-08-15',
    requirements: ['Grades 9-12', 'Good communication'],
    benefits: ['Volunteer hours', 'Leadership certificate'],
    link: 'https://example.com/volunteer',
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-opp-6',
    title: 'International Math Olympiad',
    description: 'National selection for International Mathematical Olympiad.',
    category: 'STEM',
    format: 'offline',
    grade_min: 9,
    grade_max: 11,
    deadline: '2026-09-01',
    requirements: ['Grades 9-11', 'Advanced math skills'],
    benefits: ['Medals', 'University recognition'],
    link: 'https://example.com/imo',
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'mock-course-1',
    title: 'English for Academic Success',
    description: 'Improve your academic English skills for university applications and standardized tests.',
    category: 'Languages',
    level: 'beginner',
    duration_hours: 12,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    lessons: [
      {
        id: 'l1',
        course_id: 'mock-course-1',
        title: 'Academic Writing Basics',
        video_url: 'https://www.youtube.com/embed/TFXcVlKqPlA',
        video_type: 'youtube',
        order_index: 0,
        quiz_questions: [
          { question: 'What is a thesis statement?', options: ['A fact', 'A main argument', 'A question', 'A summary'], correct: 1 },
        ],
        materials: [],
        is_published: true,
        created_at: new Date().toISOString(),
      },
      {
        id: 'l2',
        course_id: 'mock-course-1',
        title: 'Reading Comprehension',
        video_url: 'https://www.youtube.com/embed/9bZkp7q19f0',
        video_type: 'youtube',
        order_index: 1,
        quiz_questions: [],
        materials: [],
        is_published: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-course-2',
    title: 'Introduction to Economics',
    description: 'Understand basic economic principles: supply, demand, markets, and policy.',
    category: 'Business',
    level: 'beginner',
    duration_hours: 10,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    lessons: [
      {
        id: 'l3',
        course_id: 'mock-course-2',
        title: 'Supply and Demand',
        video_url: 'https://www.youtube.com/embed/MNBn6HevhvY',
        video_type: 'youtube',
        order_index: 0,
        quiz_questions: [
          { question: 'What happens when demand increases?', options: ['Price falls', 'Price rises', 'Nothing', 'Supply falls'], correct: 1 },
        ],
        materials: [],
        is_published: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-course-3',
    title: 'Computer Science Fundamentals',
    description: 'Learn programming basics, algorithms, and computational thinking.',
    category: 'Programming',
    level: 'intermediate',
    duration_hours: 18,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    lessons: [
      {
        id: 'l4',
        course_id: 'mock-course-3',
        title: 'Introduction to Algorithms',
        video_url: 'https://www.youtube.com/embed/rL8X2mlNHPM',
        video_type: 'youtube',
        order_index: 0,
        quiz_questions: [
          { question: 'Which sort has O(n log n) average case?', options: ['Bubble sort', 'Quick sort', 'Insertion sort', 'Selection sort'], correct: 1 },
        ],
        materials: [],
        is_published: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
];
